#!/usr/bin/env ruby
$LOAD_PATH.unshift File.expand_path('../lib', __FILE__)
require 'jenkinslight'
require 'serialport'

port = SerialPort.new "COM4" #"/dev/tty.usbserial-A9GNFDHP"
trafficLight = JenkinsLight::TrafficLight.new port
app = JenkinsLight::Monitor.new(STDOUT, STDIN, trafficLight)
app.url = "https://builds.apache.org/job/Accumulo-Trunk"

app.start

until false do
  sleep(5)
  app.update
end
